name: Linter

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Format Deno
        run: deno fmt --check src/**
      - name: Lint Deno
        run: deno lint
